version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      phoenix:
        patterns:
          - "bandit"
          - "phoenix"
          - "phoenix_*"
      opentelemetry:
        patterns:
          - "opentelemetry"
          - "opentelemetry_*"
      oban:
        patterns:
          - "oban"
          - "oban_*"
      tower:
        patterns:
          - "tower_*"
      all:
        patterns:
          - "*"
